---
- name: Install Node Exporter on all VMs
  hosts: all
  become: true
  tasks:
    - name: Download Node Exporter binary
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move binary to /usr/local/bin
      ansible.builtin.command:
        cmd: mv /tmp/node_exporter-1.8.2.linux-amd64/node_exporter /usr/local/bin/node_exporter
      args:
        creates: /usr/local/bin/node_exporter

    - name: Create node_exporter service
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          User=nobody
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: true
